import React from 'react';
import {View, Text, Image, TouchableNativeFeedback, ActivityIndicator, Dimensions, TouchableWithoutFeedback, ScrollView, BackHandler} from 'react-native';
import BackHeader from '../../components/atoms/BackHeader';
import { scale } from '../../theme/metric';

class PrivacyPolicyScreen extends React.Component {

    render() {
        return(
            <View style={{flex:1, backgroundColor: 'white'}} >
                <View style={{height:scale(40),backgroundColor:'white', flexDirection:'row',paddingHorizontal:scale(20)}} >
                        <BackHeader 
                            onBackPress={() => {
                                this.props.navigation.navigate("Profile")
                            }} 
                            showBackBtn={true} />
                </View>
                <View style={{height:scale(10), backgroundColor : "white"}} />
                <ScrollView style={{backgroundColor:'white', paddingHorizontal:scale(20)}}>
                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >Privacy Policy:</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We at Health Highway Private Limited ('Health Highway’', 'We', 'Us', 'Our') know that you as a user ('You', 'Your', ‘User(s)’) care about how your personal information is used and shared, and we take your privacy seriously. Please read the following to learn more about our privacy policy. By visiting or using our website (website link) and domain name, and any other linked pages, features, content, mobile applications, or any other services we offer from time to time by in connection therewith (collectively, the 'Mobile App'), or by using the Services / Products (as defined in our link to terms of use) in any manner, you acknowledge that you accept the practices and policies outlined in this privacy policy, and you hereby consent that we will collect, use, and share your information in the following ways.</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >What does this privacy policy cover?</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >This privacy policy covers our treatment of personally identifiable information ('personal information') that we gather when you are accessing or using our Mobile App and Products. This policy does not apply to the practices of companies that we do not own or control, or to individuals that we do not employ or manage. We do not knowingly collect or solicit personal information from anyone under the age of 18 or knowingly allow such persons to register for the Products. If you are under 18, please do not attempt to register for the Products or send any information about yourself to us, including your name, address, telephone number, email address or provide your biometric information. No one under age 18 may provide any personal information to us or on the Products. In the event that we learn that we have collected personal information from a child under age 18 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 18, please contact us at healthhighway2020@gmail.com</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >What information does Health Highway collect?</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We gather various types of personal information from our users, as explained more fully below. We may use this personal information to personalize and improve our services, to allow our users to set up a user account and profile, to contact users, to fulfill your requests for certain products and services, to analyze how users utilize the Mobile App and Product, and as otherwise set forth in this privacy policy. We may share certain types of personal information with third parties. We collect the following types of information:</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Information collected automatically:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >Whenever you interact with our Mobile App, we automatically receive and record information on our server logs from your browser including your IP address, 'cookie' information, and the page you requested. 'Cookies' are identifiers we transfer to your computer or mobile device that allow us to recognize your browser or mobile device and tell us how and when pages in our Mobile App are visited and by how many people. You may be able to change the preferences on your browser or mobile device to prevent or limit your computer or device's acceptance of cookies, but this may prevent you from taking advantage of our Mobile App's best features. When we collect usage information (such as the numbers and frequency of visitors to the Mobile App), we only use this data in aggregate form, and not in a manner that would identify you personally. For example, this aggregate data tells us how often users use parts of the Mobile App, so that we can make the Mobile App appealing to as many users as possible. We may also provide this aggregate information to our partners; our partners may use such information to understand how often people use our Mobile App, so that they, too, can provide you with an optimal online experience. We never disclose aggregate information to a partner in a manner that would identify you personally. If you are using our Products, you understand and acknowledge that, any information, data or readings from the Product, or collected from your use thereof, will be automatically uploaded to your account with us. To the extent these automatically collected readings can be used to personally identify you, these readings are personal information for the purposes of this privacy policy.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Delete targeting cookies:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >Your interest profile can be removed by deleting your browser's cookies.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Information stored on cookies</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >The cookie information stored on the User's hard drive is: (i) User segment hits or information on a specific product, service, brand or model in which the User has shown interest during its visit to a certain website and (ii) time and date stamp of the latest update of the User profile. If the cookie is deleted by the User, all profile data is removed. For the sake of clarity, no segments relating to information which Health Highway considers sensitive have been or will be created, such as segments relating to political opinions, religious beliefs, physical or mental health conditions or sexual life. Further, Health Highway is very sensitive to the issue of children's privacy and marketing directed to children. No segments are intended to be established for the profiling of children.</Text>


                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >E-mail and other communications:</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We may contact you, by email or other means; for example, we may send you promotional offers on behalf of other businesses, or communicate with you about your use of the Mobile App or the Product. Also, we may receive a confirmation when you open an email from us. This confirmation helps us make emails more interesting and improve our service. If you do not want to receive email or other mail from us, please indicate your preference by emailing us at healthhighway2020@gmail.com .</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >Sharing Personal Information</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We neither rent nor sell your personal information in personally identifiable form to anyone. We share your personal information in personally identifiable form with third parties only as described below. In terms of the Diverse Services, the Company shall share the information collected from You with only such third parties in relation to whom you provide express consent.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Affiliated businesses and third-party websites we do not control:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >In certain situations, businesses or third party websites we're affiliated with may sell items or provide services to you through the Mobile App (either alone or jointly with us). You can recognize when an affiliated business is associated with such a transaction or service, and we will share your personal information with that affiliated business only to the extent that it is related to such transaction or service.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Agents:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We employ other companies and people to perform tasks on our behalf and need to share your information with them to provide Products or services to you. Unless we tell you differently, our agents do not have any right to use the personal information we share with them beyond what is necessary to assist us.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• User submissions:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >Any content or personal information that you voluntarily disclose online in a manner other users can view (on discussion boards, in messages and chat areas, etc.) becomes publicly available, and can be collected and used by others.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Business transfers:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We may choose to buy or sell assets. In these types of transactions, customer information is typically one of the business assets that is transferred. Also, if we (or substantially all of our assets) are acquired, or if we go out of business or enter bankruptcy, personal information would be one of the assets transferred to or acquired by a third party.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• Protection of Health Highway and others:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We may release personal information when we believe in good faith that release is necessary to comply with laws; enforce or apply our conditions of use and other agreements; or protect the rights, property, or safety of Health Highway, our employees, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction.</Text>

                        <Text allowFontScaling={false} style={{fontSize:scale(18), fontWeight:"bold", fontFamily:'Montserrat-Semibold'}} >• With your consent:</Text>
                        <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >Except as set forth above, you will be notified when your personal information may be shared with third parties, and will be able to prevent the sharing of this information.</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >What personal information can ‘you’ access?</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >Through your account settings, you may access, and, in some cases, edit or delete the following information you've provided to us:

name and password
email address
user profile information, including your height, weight, and location
The information you can view and update may change as the Mobile App changes. Please note that any information that is automatically uploaded from a Product to the Mobile App, or collected otherwise from You by us, cannot be later changed or updated. If you have any questions about viewing or updating information we have on file about you, please contact us at: healthhighway2020@gmail.com.</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >What choices do ‘you’ have?</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >You can always opt not to disclose information to use, but keep in mind some information may be needed to register with us or to take advantage of some of our special features / Products. We will retain Your personal information for a reasonable period or as long as the law requires. If you’d like us to delete/modify Information that you have provided via the Mobile App or otherwise to us, please contact us at healthhighway2020@gmail.com and we will respond in a reasonable time. Please note that some or all of the Information provided by You to us may be required in order for the Mobile App / Products to function properly. You may be able to add, update, or delete information as explained in section above. When you update information, however, we may maintain a copy of the unrevised information in our records. Please note that some information may remain in our private records after your deletion of such information from your account. We may use any aggregated data derived from or incorporating your personal information after you update or delete it, but not in a manner that would identify you personally. If you do not wish to receive email or other mail from us, please email us at: healthhighway2020@gmail.com . Please note that if you do not want to receive legal notices from us, such as this privacy policy, those legal notices will still govern your use of the Mobile App and the Product, and you are responsible for reviewing such legal notices for changes.</Text>

                    <Text allowFontScaling={false} style={{fontSize:scale(20), fontWeight:"bold", fontFamily:'Montserrat-Semibold' }} >Changes to this privacy policy</Text>
                    <Text allowFontScaling={false} style={{fontSize:scale(16), fontFamily:'Montserrat-Regular', marginVertical:scale(20) }} >We may amend this privacy policy from time to time. Use of information we collect now is subject to the privacy policy in effect at the time such information is used. If we make changes in the way we use personal information, we will notify you by posting an announcement on our Mobile App or sending you an email. You are bound by any changes to the privacy policy when you use the Mobile App or the Product after such changes have been first posted. How is my iOS HealthKit, Health app and Google Fit data handled? When you share your iOS Health app data or Google Fit with our Products, that data is covered by the privacy policy. We handle all iOS Health app and HealthKit data in accordance with Apple's development guidelines. To view Apple's HealthKit developer guidelines, go to https://developer.apple.com/app-store/review/guidelines/#health-and-health-research . We handle Google Fit data in accordance with Google Fit Terms of Service. To view Google Fit Terms of Service go to https://developers.google.com/fit/terms . HealthKit, Health app, iPhone, and Apple are registered trademarks of Apple Inc. Google Fit and Google are registered trademark of Google Inc</Text>

                </ScrollView>
            </View>
        )
    }
}

export default PrivacyPolicyScreen;